version : '3'
services: # Services to deploy
  
  api:
    image: api #image name, Default:- Folder Name
    ports:
      - "4000:8080"
  api2:
    image: api
    ports:
      - "4001:8080"
  yarp:
    image: yarp
    ports:
      - "8002:8080"
